[WIP] #13: Sección de introducción
lulivi/deep-g-prop pull request #20
Opened 2019-10-07 20:32 UTC by lulivi

Trabajo en curso. No *mergeable*.

Este *Pull-request* cierra el Issue #13.

2019-10-15 05:29 UTC, JJ requested changes
En general está bien, pero ten en cuenta que en un TFG tienes que aportar código y también intenta definir todo lo que uses.

2019-10-15 05:29 UTC, JJ commented on docs/report/secciones/01_introduccion.texw
> +A parte de los objetivos básicos del proyecto como elegir frameworks tanto de
Elegir o programar.

2019-10-15 05:29 UTC, JJ commented on docs/report/secciones/01_introduccion.texw
> +\item Evitar sobreajuste en este tipo de configuraciones.
Define sobreajuste.

2019-10-15 20:19 UTC, lulivi commented on docs/report/secciones/01_introduccion.texw
> +A parte de los objetivos básicos del proyecto como elegir frameworks tanto de
Realmente sería elegir un framework para programar los MLP y GAs, ¿no? Es decir, que lo he explicado mal.

2019-10-16 16:28 UTC, JJ commented on docs/report/secciones/01_introduccion.texw
> +A parte de los objetivos básicos del proyecto como elegir frameworks tanto de
Si ninguno de los que hay está bien, siempre está la alternativa de programarlo.

2019-11-06 11:04 UTC, JJ approved these changes
Tendré que verlo en su contexto, pero por lo pronto parece que está bien.

2019-11-06 11:05 UTC, merged